# Generated by Django 6.0.3 on 2026-05-12 10:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_clientes_seguimiento', '0004_cliente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_usuario', models.TextField(blank=True, null=True)),
                ('imagen_referencia', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('audio_descripcion', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video')),
                ('respuesta_ia', models.TextField(blank=True, null=True)),
                ('transcripcion_audio', models.TextField(blank=True, null=True)),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasaciones_ia', to='modulo_clientes_seguimiento.cliente')),
            ],
            options={
                'db_table': 'tasaciones_ia',
                'ordering': ['-creado_en'],
            },
        ),
    ]
