# Generated by Django 6.0.3 on 2026-05-14 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_clientes_seguimiento', '0005_cliente_tenant'),
        ('modulo_tasacion_ia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacionia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasaciones_ia', to='modulo_clientes_seguimiento.cliente'),
        ),
    ]
