# Generated by Django 6.0.3 on 2026-05-14 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_tasacion_ia', '0002_alter_tasacionia_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasacionia',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasaciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
