# Generated by Django 6.0.3 on 2026-05-27 10:22

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_tasacion_ia', '0003_tasacionia_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaSemanticaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_texto', models.TextField(blank=True, null=True)),
                ('audio_busqueda', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video')),
                ('filtros_extraidos_ia', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='busquedas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'busquedas_semanticas_ia',
                'ordering': ['-creado_en'],
            },
        ),
    ]
