import axios from "axios";

// PARA PODER CONECTAR CON EL BACKEND,
// CREAR UN ARCHIVO .ENV EN LA RAIZ DEL PROYECTO Y AGREGAR LA VARIABLE VITE_APP_BASE_URL CON LA URL DE TU BACKEND
// EJEMPLO: VITE_APP_BASE_URL=http://localhost:8080


export const intanciaAxios = axios.create({
  baseURL: import.meta.env.VITE_APP_BASE_URL || "http://localhost:8080",
  withCredentials: true, // PARA ENVIAR LAS COOKIES EN CADA PETICION, SI EL BACKEND LAS USA PARA LA AUTENTICACION

  // "TODO" PARA DENNIS.
  // TODO: AGREGAR CONFIG PARA LAS CORS, SI ES NECESARIO.
  // TODO: CONFIGURAR LOS HEADERS, SI ES NECESARIO.
  // TODO: CONFIGURAR LOS INTERCETORES (INTERCEPTORS).
})