# Generated by Django 6.0.3 on 2026-05-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_administracion_configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('key_r2', models.CharField(max_length=255)),
                ('tamano', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Respaldo en Nube',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
