# Generated by Django 6.0.3 on 2026-05-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_administracion_configuracion', '0004_merge_20260512_2235'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_estado_a5bb45_idx',
            old_name='tenants_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_plan_b28c7a_idx',
            old_name='tenants_plan_idx',
        ),
    ]
