# Generated by Django 5.2.1 on 2026-05-13 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_administracion_configuracion', '0005_rename_tenants_estado_idx_tenants_estado_a5bb45_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_checkout_id', models.CharField(max_length=255, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='usd', max_length=10)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('plan_adquirido', models.CharField(max_length=50)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='modulo_administracion_configuracion.tenant')),
            ],
        ),
    ]
