# Generated by Django 6.0.3 on 2026-05-09 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_clientes_seguimiento', '0001_initial'),
        ('modulo_inmuebles', '0003_agregar_campos_faltantes_propiedad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDisponibilidad',
            fields=[
                ('id_horario', models.BigAutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('propiedad', models.ForeignKey(db_column='id_propiedad', on_delete=django.db.models.deletion.CASCADE, related_name='horarios_visita', to='modulo_inmuebles.propiedad')),
            ],
            options={
                'verbose_name': 'Horario de Disponibilidad',
                'verbose_name_plural': 'Horarios de Disponibilidad',
                'db_table': 'propiedad_horarios_visita',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_visita', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('comentario_cliente', models.TextField(blank=True, null=True)),
                ('comentario_agente', models.TextField(blank=True, null=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(db_column='id_agente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_atendidas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='modulo_clientes_seguimiento.cliente')),
                ('propiedad', models.ForeignKey(db_column='id_propiedad', on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='modulo_inmuebles.propiedad')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'db_table': 'propiedad_visitas',
            },
        ),
    ]
