# Generated by Django 6.0.3 on 2026-05-09 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_clientes_seguimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-creado_en']},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('seguimiento', 'En seguimiento'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('cerrado', 'Cerrado')], default='nuevo', max_length=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='origen',
            field=models.CharField(blank=True, choices=[('web', 'Web'), ('movil', 'Móvil'), ('referido', 'Referido'), ('agente', 'Agente'), ('campana', 'Campaña')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ClienteInteraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('visita', 'Visita'), ('llamada', 'Llamada'), ('mensaje', 'Mensaje'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('asunto', models.CharField(blank=True, max_length=150, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('proxima_accion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_proxima_accion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='modulo_clientes_seguimiento.cliente')),
            ],
            options={
                'db_table': 'cliente_interacciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ClienteOportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('etapa', models.CharField(choices=[('prospecto', 'Prospecto'), ('interesado', 'Interesado'), ('negociacion', 'Negociación'), ('cerrado', 'Cerrado'), ('perdido', 'Perdido')], default='prospecto', max_length=15)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('probabilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_cierre_est', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='modulo_clientes_seguimiento.cliente')),
            ],
            options={
                'db_table': 'cliente_oportunidades',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ClienteRecordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_recordatorio', models.DateTimeField()),
                ('atendido', models.BooleanField(default=False)),
                ('atendido_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='modulo_clientes_seguimiento.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cliente_recordatorios',
                'ordering': ['fecha_recordatorio'],
            },
        ),
        migrations.CreateModel(
            name='ClienteAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes', to='modulo_clientes_seguimiento.cliente')),
            ],
            options={
                'db_table': 'cliente_agente',
                'unique_together': {('cliente', 'agente')},
            },
        ),
    ]
