# Generated by Django 6.0.3 on 2026-03-30 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadSistema',
            fields=[
                ('id_actividad', models.BigAutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=50)),
                ('entidad', models.CharField(max_length=50)),
                ('id_entidad', models.BigIntegerField(blank=True, null=True)),
                ('accion', models.CharField(max_length=50)),
                ('detalle', models.TextField()),
                ('ip_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'actividad_sistema',
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
