# Generated by Django 6.0.3 on 2026-03-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_actividadsistema'),
        ('gestion_usuarios', '0002_usuario_ci_usuario_direccion_and_more'),
    ]

    operations = [
    ]
