# Generated by Django 6.0.3 on 2026-05-12 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_merge_20260330_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agencia',
                'verbose_name_plural': 'Agencias',
                'db_table': 'agencias',
            },
        ),
        migrations.AddField(
            model_name='actividadsistema',
            name='agencia',
            field=models.ForeignKey(db_column='id_agencia', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.agencia'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='agencia',
            field=models.ForeignKey(db_column='id_agencia', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.agencia'),
        ),
        migrations.AddField(
            model_name='rol',
            name='agencia',
            field=models.ForeignKey(db_column='id_agencia', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.agencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='agencia',
            field=models.ForeignKey(blank=True, db_column='id_agencia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='gestion_usuarios.agencia'),
        ),
    ]
