# Generated by Django 6.0.3 on 2026-05-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0004_agencia_actividadsistema_agencia_permiso_agencia_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rol',
            unique_together={('nombre', 'agencia')},
        ),
    ]
