# Generated by Django 6.0.3 on 2026-05-12 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0006_alter_rol_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_propiedades', models.IntegerField(default=10)),
                ('limite_agentes', models.IntegerField(default=3)),
                ('permite_ia', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='agencia',
            name='configuracion',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agencia',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('id_transaccion_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='gestion_usuarios.agencia')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_usuarios.plan')),
            ],
        ),
    ]
