# Generated by Django 6.0.3 on 2026-05-08 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_inmuebles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_contrato', models.CharField(max_length=30, unique=True)),
                ('tipo_operacion', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('ALQUILER', 'Alquiler'), ('ANTICRETICO', 'Anticrético')], max_length=20)),
                ('estado_contrato', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido'), ('RENOVADO', 'Renovado'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('garantia', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('condiciones', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(db_column='id_agente', on_delete=django.db.models.deletion.PROTECT, related_name='contratos_agente', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='contratos_cliente', to=settings.AUTH_USER_MODEL)),
                ('propiedad', models.ForeignKey(db_column='id_propiedad', on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='modulo_inmuebles.propiedad')),
                ('renovacion_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_contratos.contrato')),
            ],
            options={
                'db_table': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoContrato',
            fields=[
                ('id_documento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('archivo_url', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='modulo_contratos.contrato')),
            ],
            options={
                'db_table': 'documentos_contrato',
            },
        ),
        migrations.CreateModel(
            name='PagoContrato',
            fields=[
                ('id_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='modulo_contratos.contrato')),
            ],
            options={
                'db_table': 'pagos_contrato',
            },
        ),
    ]
