# Generated by Django 6.0.3 on 2026-05-28 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_administracion_configuracion', '0005_rename_tenants_estado_idx_tenants_estado_a5bb45_idx_and_more'),
        ('modulo_contratos', '0001_initial'),
        ('modulo_inmuebles', '0005_alter_propiedad_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionInmobiliaria',
            fields=[
                ('id_operacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_operacion', models.CharField(max_length=30, unique=True)),
                ('tipo_operacion', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('ALQUILER', 'Alquiler'), ('ANTICRETICO', 'Anticrético')], max_length=30)),
                ('monto_operacion', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comision_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_operacion', models.DateField()),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('anulada', 'Anulada')], default='cerrada', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, db_column='id_agente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_agente', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_cliente', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(db_column='id_moneda', on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='modulo_administracion_configuracion.moneda')),
                ('propiedad', models.ForeignKey(db_column='id_propiedad', on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='modulo_inmuebles.propiedad')),
            ],
            options={
                'db_table': 'operaciones_inmobiliarias',
            },
        ),
    ]
