# Generated by Django 6.0.3 on 2026-05-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_contratos', '0002_operacioninmobiliaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacioninmobiliaria',
            name='id_cotizacion',
            field=models.BigIntegerField(blank=True, db_column='id_cotizacion', null=True),
        ),
        migrations.AlterField(
            model_name='operacioninmobiliaria',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creada_en'),
        ),
    ]
