# Generated by Django 6.0.3 on 2026-04-11 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_administracion_configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.BigAutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(default='Bolivia', max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('zona', models.CharField(max_length=150)),
                ('barrio', models.CharField(blank=True, max_length=150, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'zonas',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id_propiedad', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_propiedad', models.CharField(max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_inmueble', models.CharField(blank=True, max_length=255, null=True)),
                ('id_modalidad', models.BigIntegerField()),
                ('modalidad_operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expensas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('superficie_total_m2', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('superficie_construida_m2', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ambientes', models.IntegerField(default=0)),
                ('dormitorios', models.IntegerField(default=0)),
                ('banos', models.IntegerField(db_column='banos', default=0)),
                ('garajes', models.IntegerField(default=0)),
                ('amoblado', models.BooleanField(default=False)),
                ('publicado_web', models.BooleanField(default=True)),
                ('publicado_movil', models.BooleanField(default=True)),
                ('destacada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades_creadas', to=settings.AUTH_USER_MODEL)),
                ('id_agente_publicador', models.ForeignKey(db_column='id_agente_publicador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades_asignadas', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(db_column='id_moneda', on_delete=django.db.models.deletion.PROTECT, to='modulo_administracion_configuracion.moneda')),
                ('zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.PROTECT, to='modulo_inmuebles.zona')),
            ],
            options={
                'db_table': 'propiedades',
            },
        ),
        migrations.CreateModel(
            name='PropiedadImagen',
            fields=[
                ('id_imagen', models.BigAutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.TextField()),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('orden_visual', models.IntegerField(default=1)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(db_column='id_propiedad', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='modulo_inmuebles.propiedad')),
            ],
            options={
                'db_table': 'propiedad_imagenes',
                'ordering': ['orden_visual'],
            },
        ),
    ]
