# Generated by Django 6.0.3 on 2026-05-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
