# Generated by Django 6.0.3 on 2026-05-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_inmuebles', '0002_propiedad_latitud_propiedad_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='antiguedad_anios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='caracteristicas_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='comision_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='estado_propiedad',
            field=models.CharField(blank=True, default='Disponible', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='pisos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='promocionada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='servicios_basicos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
