# Generated by Django 6.0.3 on 2026-05-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_inmuebles', '0002_propiedad_tenant'),
        ('modulo_inmuebles', '0003_agregar_campos_faltantes_propiedad'),
    ]

    operations = [
    ]
