# Generated by Django 6.0.3 on 2026-05-13 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_administracion_configuracion', '0005_rename_tenants_estado_idx_tenants_estado_a5bb45_idx_and_more'),
        ('modulo_inmuebles', '0004_merge_20260512_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='modulo_administracion_configuracion.tenant'),
        ),
    ]
